#!/bin/bash

PASSWD=~/Passwd

rsync --progress --size-only --password-file=$PASSWD  --copy-links --delete-during -rlpgoDv -hh --stats --inplace -B 65536 --address 74.114.99.134 /XRaid/share/private/ cistrack@74.114.99.127::cistracksync

